kiss = [
    "{zao} says that :flag_pt: ronaldo :fire: > :flag_ar: messi :x: and {user} agrees :+1:",
    "{user} gives {zao} a soft kiss :kiss:",
    "{user} plants a gentle kiss on {zao}'s cheek :heartbeat:",
    "{zao} messi gol! :goal: ... {user} is not impressed :unamused:",
    "{zao} zostaje zabity tępym narzędziem przez {user} :hammer:",
    "{user} gives {zao} you a quick peck on the forehead :heartpulse:",
    "{user} shares a loving kiss with {zao} :heart:",
    "{zao} gently kisses {user} hand :lips:",
    "{zao} ty draniu :broken_heart: :sob: {user}",
    "{user} is gonna touch you {zao} :palm_up_hand:",
    "{user} kisses {zao} warmly :kissing_heart:",
    "{user} dreams about {zao} without a shirt :sweat_drops::sweat_drops::sweat_drops:",
    "{user} wali spuche na {zao} :face_with_spiral_eyes:",
    "{user} hugs {zao} tightly :hugs:",
    "{user} and {zao} share a secret smile :smirk:",
    "{user} winks at {zao} :wink:",
    "{user} and {zao} dance together :dancer::man_dancing:",
    "{user} and {zao} share a moment of silence :shushing_face:",
    "{user} and {zao} stroke together :joy:",
]

country_codes = [
    # Supported locales (keep these)
    "en",
    "pl",
    "de",
    "es",
    "fr",
    "pt",

    # The following locales are currently not supported — kept here commented for reference
    # "ar",
    # "bg",
    # "cs",
    # "da",
    # "el",
    # "fi",
    # "he",
    # "hi",
    # "hu",
    # "it",
    # "ja",
    # "ko",
    # "nl",
    # "no",
    # "ro",
    # "ru",
    # "sv",
    # "tr",
    # "uk",
    # "vi",
    # "zh",
]
