from discord import app_commands
from typing import Any, Dict


class RobakTranslator(app_commands.Translator):
    # use string keys for locales to avoid runtime/pyright issues with app_commands.Locale
    translation_dict: Dict[str, Dict[str, str]] = {
        "polish": {
            "pl": "",
            "group.robak.name": "robak",
            "group.robak.description": "Komendy pseudonimów robaka",
            "command.generate.name": "generuj",
            "command.generate.description": "Generuje pseudonim i pozwala wybrać, czy chcesz go zastosować",
            "command.add.name": "dodaj",
            "command.add.description": "Dodaje pseudonim do listy",
            "option.nickname.name": "pseudonim",
            "option.nickname.description": "Pseudonim, który ma być dodany do listy",
            "command.remove.name": "usuń",
            "command.remove.description": "Usuwa pseudonim z listy",
            "command.all.name": "wszystkie",
            "command.all.description": "Wyświetla wszystkie zapisane pseudonimy",
            "command.last.name": "ostatnie",
            "command.last.description": "Wyświetla ostatnio wygenerowane pseudonimy",
            "command.endorsed.name": "popierane",
            "command.endorsed.description": "Wyświetla najbardziej popierane pseudonimy",
            "command.setlang.name": "ustaw-język",
            "command.setlang.description": "Ustawia preferowany język dla serwera",
            "option.lang.name": "język",
            "option.lang.description": "Kod języka, na przykład en lub pl",
            "command.generate-zao.name": "generuj-zao",
            "command.generate-zao.description": "Generuje pseudonim dla Żao",
            "command.kiss.name": "pocałuj",
            "command.kiss.description": "Wysyła całusa",
            "option.member.name": "użytkownik",
            "option.member.description": "Opcjonalny użytkownik, do którego wysłać całusa",
            "command.balls.name": "balls",
            "command.balls.description": "balls",
            "group.blacklist.name": "czarna-lista",
            "command.blacklist.description": "Zarządzaj czarną listą słów",
            # base names for localization (must match the actual command identifiers)
            "blacklist": "czarna-lista",
            "add": "dodaj",
            "remove": "usuń",
            "list": "lista",
            "command.blacklist.add.name": "dodaj",
            "command.blacklist.add.description": "Dodaje słowo do czarnej listy",
            "command.blacklist.remove.name": "usuń",
            "command.blacklist.remove.description": "Usuwa słowo z czarnej listy",
            "command.blacklist.list.name": "lista",
            "command.blacklist.list.description": "Wyświetla zablokowane słowa",
            "option.term.name": "słowo",
            "option.term.description": "Słowo, które ma być zablokowane",
            "command.blacklist-remove.name": "czarna-lista-usuń",
            "command.blacklist-remove.description": "Usuwa słowo z czarnej listy",
            "command.blacklist-list.name": "czarna-lista-lista",
            "command.blacklist-list.description": "Wyświetla zablokowane słowa",
            "command.more.name": "więcej",
            "command.more.description": "Więcej informacji o robaku",
        },
        "german": {
            "de": "",
            # programmatic i18n keys
            "group.robak.name": "wurm",
            "group.robak.description": "Wurm Spitznamen Befehle",
            "command.generate.name": "generieren",
            "command.generate.description": "Generiere einen Spitznamen und entscheide, ob er angewendet werden soll",
            "command.add.name": "hinzufügen",
            "command.add.description": "Einen Spitznamen zur Liste hinzufügen",
            "option.nickname.name": "spitzname",
            "option.nickname.description": "Hinzuzufügender Spitzname",
            "command.remove.name": "entfernen",
            "command.remove.description": "Einen Spitznamen aus der Liste entfernen",
            "command.all.name": "alle",
            "command.all.description": "Alle Spitznamen auflisten",
            "command.last.name": "letzte",
            "command.last.description": "Die letzten generierten Spitznamen auflisten",
            "command.endorsed.name": "unterstützt",
            "command.endorsed.description": "Die am meisten unterstützten Spitznamen auflisten",
            "command.setlang.name": "sprache-einstellen",
            "command.setlang.description": "Die bevorzugte Sprache einstellen",
            "option.lang.name": "sprache",
            "option.lang.description": "Sprachcode, zum Beispiel en oder pl",
            "command.generate-zao.name": "generiere-zao",
            "command.generate-zao.description": "Generiere einen Spitznamen für Żao",
            "command.kiss.name": "küssen",
            "command.kiss.description": "Einen Kuss senden",
            "option.member.name": "mitglied",
            "option.member.description": "Optionales Mitglied als Ziel",
            "command.balls.name": "balls",
            "command.balls.description": "balls",
            "group.blacklist.name": "blacklist",
            "command.blacklist.description": "Verwalte die Blacklist",
            # base names for localization (must match the actual command identifiers)
            "blacklist": "blacklist",
            "add": "hinzufügen",
            "remove": "entfernen",
            "list": "liste",
            "command.blacklist.add.name": "hinzufügen",
            "command.blacklist.add.description": "Einen Begriff zur Blacklist hinzufügen",
            "command.blacklist.remove.name": "entfernen",
            "command.blacklist.remove.description": "Einen Begriff von der Blacklist entfernen",
            "command.blacklist.list.name": "liste",
            "command.blacklist.list.description": "Gesperrte Begriffe auflisten",
            "option.term.name": "begriff",
            "option.term.description": "Begriff, der auf die Blacklist gesetzt werden soll",
            "command.blacklist-remove.name": "blacklist-entfernen",
            "command.blacklist-remove.description": "Einen Begriff von der Blacklist entfernen",
            "command.blacklist-list.name": "blacklist-liste",
            "command.blacklist-list.description": "Gesperrte Begriffe auflisten",
            "command.more.name": "mehr",
            "command.more.description": "Mehr Informationen über den Wurm",
        },
        "spain_spanish": {
            "es": "",
            # programmatic i18n keys
            "group.robak.name": "gusano",
            "group.robak.description": "Comandos de apodos de gusano",
            "command.generate.name": "generar",
            "command.generate.description": "Genera un apodo y elige si aplicarlo",
            "command.add.name": "añadir",
            "command.add.description": "Añade un apodo a la lista",
            "option.nickname.name": "apodo",
            "option.nickname.description": "Apodo a añadir",
            "command.remove.name": "eliminar",
            "command.remove.description": "Elimina un apodo de la lista",
            "command.all.name": "todos",
            "command.all.description": "Muestra todos los apodos",
            "command.last.name": "ultimos",
            "command.last.description": "Muestra los últimos apodos generados",
            "command.endorsed.name": "apoyados",
            "command.endorsed.description": "Muestra los apodos más apoyados",
            "command.setlang.name": "establecer-idioma",
            "command.setlang.description": "Establece el idioma preferido",
            "option.lang.name": "idioma",
            "option.lang.description": "Código de idioma, por ejemplo en o pl",
            "command.generate-zao.name": "generar-zao",
            "command.generate-zao.description": "Genera un apodo para Żao",
            "command.kiss.name": "besar",
            "command.kiss.description": "Envía un beso",
            "option.member.name": "miembro",
            "option.member.description": "Miembro opcional al que besar",
            "command.balls.name": "balls",
            "command.balls.description": "balls",
            "group.blacklist.name": "lista-negra",
            "command.blacklist.description": "Gestiona la lista negra",
            # base names for localization (must match the actual command identifiers)
            "blacklist": "lista-negra",
            "add": "añadir",
            "remove": "eliminar",
            "list": "listar",
            "command.blacklist.add.name": "añadir",
            "command.blacklist.add.description": "Añade un término a la lista negra",
            "command.blacklist.remove.name": "eliminar",
            "command.blacklist.remove.description": "Elimina un término de la lista negra",
            "command.blacklist.list.name": "listar",
            "command.blacklist.list.description": "Muestra los términos bloqueados",
            "option.term.name": "termino",
            "option.term.description": "Término a bloquear",
            "command.blacklist-remove.name": "lista-negra-eliminar",
            "command.blacklist-remove.description": "Elimina un término de la lista negra",
            "command.blacklist-list.name": "lista-negra-listar",
            "command.blacklist-list.description": "Muestra los términos bloqueados",
            "command.more.name": "mas",
            "command.more.description": "Más información sobre el gusano",
        },
        "french": {
            "fr": "",
            "group.robak.name": "ver",
            "group.robak.description": "Commandes de surnom de ver",
            "command.generate.name": "generer",
            "command.generate.description": "Générer un surnom et choisir de l'appliquer",
            "command.add.name": "ajouter",
            "command.add.description": "Ajouter un surnom à la liste",
            "option.nickname.name": "surnom",
            "option.nickname.description": "Surnom à ajouter",
            "command.remove.name": "supprimer",
            "command.remove.description": "Supprimer un surnom de la liste",
            "command.all.name": "tout",
            "command.all.description": "Afficher tous les surnoms",
            "command.last.name": "derniers",
            "command.last.description": "Afficher les derniers surnoms générés",
            "command.endorsed.name": "soutenus",
            "command.endorsed.description": "Afficher les surnoms les plus soutenus",
            "command.setlang.name": "configurer-langue",
            "command.setlang.description": "Définir la langue préférée",
            "option.lang.name": "langue",
            "option.lang.description": "Code langue, par exemple en ou pl",
            "command.generate-zao.name": "generer-zao",
            "command.generate-zao.description": "Générer un surnom pour Żao",
            "command.kiss.name": "embrasser",
            "command.kiss.description": "Envoyer un baiser",
            "option.member.name": "membre",
            "option.member.description": "Membre optionnel à cibler",
            "command.balls.name": "balls",
            "command.balls.description": "balls",
            "group.blacklist.name": "liste-noire",
            "command.blacklist.description": "Gérez la liste noire",
            # base names for localization (must match the actual command identifiers)
            "blacklist": "liste-noire",
            "add": "ajouter",
            "remove": "supprimer",
            "list": "lister",
            "command.blacklist.add.name": "ajouter",
            "command.blacklist.add.description": "Ajouter un terme à la liste noire",
            "command.blacklist.remove.name": "supprimer",
            "command.blacklist.remove.description": "Supprimer un terme de la liste noire",
            "command.blacklist.list.name": "lister",
            "command.blacklist.list.description": "Afficher les termes bloqués",
            "option.term.name": "terme",
            "option.term.description": "Terme à bloquer",
            "command.blacklist-remove.name": "liste-noire-supprimer",
            "command.blacklist-remove.description": "Supprimer un terme de la liste noire",
            "command.blacklist-list.name": "liste-noire-lister",
            "command.blacklist-list.description": "Afficher les termes bloqués",
            "command.more.name": "plus",
            "command.more.description": "Plus d'informations sur le ver",
        },
        # Empty template to copy when adding a new locale
        # "template": {
        #    "{language_code}": "",
        #    "group.robak.name": "",
        #    "group.robak.description": "",
        #    "command.generate.name": "",
        #    "command.generate.description": "",
        #    "command.add.name": "",
        #    "command.add.description": "",
        #    "option.nickname.name": "",
        #    "option.nickname.description": "",
        #    "command.remove.name": "",
        #    "command.remove.description": "",
        #    "command.all.name": "",
        #    "command.all.description": "",
        #    "command.last.name": "",
        #    "command.last.description": "",
        #    "command.endorsed.name": "",
        #    "command.endorsed.description": "",
        #    "command.setlang.name": "",
        #    "command.setlang.description": "",
        #    "option.lang.name": "",
        #    "option.lang.description": "",
        #    "command.generate-zao.name": "",
        #    "command.generate-zao.description": "",
        #    "command.kiss.name": "",
        #    "command.kiss.description": "",
        #    "option.member.name": "",
        #    "option.member.description": "",
        #    "command.balls.name": "",
        #    "command.balls.description": "",
        #    "group.blacklist.name": "",
        #    "command.blacklist.description": "",
        #    "blacklist": "",
        #    "add": "",
        #    "remove": "",
        #    "list": "",
        #    "command.blacklist.add.name": "",
        #    "command.blacklist.add.description": "",
        #    "command.blacklist.remove.name": "",
        #    "command.blacklist.remove.description": "",
        #    "command.blacklist.list.name": "",
        #    "command.blacklist.list.description": "",
        #    "option.term.name": "",
        #    "option.term.description": "",
        #    "command.blacklist-remove.name": "",
        #    "command.blacklist-remove.description": "",
        #    "command.blacklist-list.name": "",
        #    "command.blacklist-list.description": "",
        #    "command.more.name": "",
        #    "command.more.description": "",
        # },
    }

    async def translate(
        self,
        string: app_commands.locale_str,
        locale: Any,
        context: app_commands.TranslationContext[Any, Any],
    ) -> str | None:
        raw = None
        if hasattr(locale, "name"):
            raw = str(getattr(locale, "name")).lower()
        elif hasattr(locale, "value"):
            raw = str(getattr(locale, "value")).lower()
        else:
            raw = str(locale).lower()

        # Mark `context` as used to satisfy static analyzers
        _ = context

        translations = self.translation_dict.get(raw) or None
        if translations is None:
            # check each mapping for an alias match
            for key, mapping in self.translation_dict.items():
                if raw == key or raw.startswith(key) or raw in mapping:
                    translations = mapping
                    break
        if translations:
            return translations.get(string.message)
        return None


